version: 2

models:
  - name: dim_comics
    description: "Dimension table for comic information."
    columns:
      - name: comic_id
        description: "Unique identifier for the comic."
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the comic."
        tests:
          - not_null
      - name: safe_title
        description: "Safe title (no special characters or unwanted words)."
      - name: link
        description: "Link to the comic online."
      - name: img
        description: "Link to the comic image."
      - name: alt
        description: "Alt text for the comic image."
      - name: transcript
        description: "Transcript of the comic."
      - name: news
        description: "News related to the comic."

  - name: dim_date
    description: "Dimension table for date-related information."
    columns:
      - name: id
        description: "Unique identifier for the date in the format YYYYMMDD."
        tests:
          - unique
          - not_null
      - name: year
        description: "Year part of the date."
      - name: month
        description: "Month part of the date."
      - name: day
        description: "Day part of the date."
      - name: date
        description: "Full date in the format YYYY-MM-DD."
        tests:
          - not_null
      - name: day_of_week
        description: "Day of the week (e.g., Monday, Tuesday)."      

  - name: fact_comics
    description: "Fact table for comic related data such as cost, views, and customer reviews."
    columns:
      - name: comic_id
        description: "Unique identifier for the comic, referencing the dim_comics table."
        tests:
          - not_null
          - relationships:
              to: ref('dim_comics')
              field: comic_id

      - name: date_id
        description: "Date identifier, referencing the dim_date table."
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: id
      - name: cost
        description: "Calculated cost based on the length of the comic title."
        tests:
          - not_null
          - negative_values:
              column_name: cost
      - name: customer_reviews
        description: "Randomly generated customer reviews rating (1-10)."
        tests:
          - accepted_range:
              min: 1
              max: 10
      - name: customer_views
        description: "Randomly generated customer views (0-10000)."
        tests:
          - accepted_range:
              min: 0
              max: 10000
